# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
# write your code here
import sys
import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [2]:
# write your code here (for Python default syntax)
python_array = [0] * 1000
sys.getsizeof(python_array)

8056

In [3]:
# write your code here (for numpy syntax)
numpy_array = np.array(python_array, dtype=np.int8)
sys.getsizeof(numpy_array)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
# write your code here
float_array = np.array([0, 0.5, 1, 1.5, 2, 5.5, 6.5, 8, 10])
float_array[[0, 2, -1]]

array([ 0.,  1., 10.])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [5]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
# write your code here
array[[-1, 0, 1, -4]].sum()

27.0

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [6]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [8]:
# write your code here
A.std(axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.2 Get the standard deviation by `y` axis

In [9]:
# write your code here
A.std(axis=1)

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [10]:
# write your code here
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [14]:
# write your code here
A[:2, :2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [15]:
# write your code here
A[[0, 2, -1], :2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [34]:
# Python code
%time python_list = [i for i in range(1000000)]

CPU times: total: 15.6 ms
Wall time: 60.6 ms


In [35]:
%time len(python_list)

CPU times: total: 0 ns
Wall time: 0 ns


1000000

In [36]:
# write your numpy code here and estimate the time of execution
%time np.arange(1000000)

CPU times: total: 0 ns
Wall time: 1 ms


array([     0,      1,      2, ..., 999997, 999998, 999999])

### Task 6.2

In [19]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

CPU times: total: 0 ns
Wall time: 0 ns


0

In [20]:
# write your numpy code here and estimate the time of execution
# Numpy code
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
%time vector1.dot(vector2)

CPU times: total: 0 ns
Wall time: 0 ns


32

### Task 6.3

In [23]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%time unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


[[5, 12], [21, 32]]

In [24]:
# write your numpy code here and estimate the time of execution
# Numpy code
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

%time matrix1 * matrix2
%time np.multiply(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [25]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    mean = total / len(lst)
    return mean

%time unknown_signature([1, 2, 3, 4, 5])

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [26]:
# write your numpy code here and estimate the time of execution
# Numpy code
%time np.mean([1, 2, 3, 4, 5])

CPU times: total: 0 ns
Wall time: 0 ns


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [27]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [28]:
# write your numpy code here
lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0
lst[mask] = new_value
lst

array([0, 2, 0, 4, 0])

### Task 7.2

In [29]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [11]:
# write your numpy code here
def unknown_signature_np(lst1, lst2):
    arr1 = np.array(lst1)
    arr2 = np.array(lst2)
    
    bitwise_complement = np.bitwise_not(arr1)
    bitwise_and = np.bitwise_and(arr1, arr2)
    bitwise_or = np.bitwise_or(arr1, arr2)
    
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement_np, result_bitwise_and_np, result_bitwise_or_np = unknown_signature_np(list1, list2)

result_bitwise_complement_np, result_bitwise_and_np, result_bitwise_or_np

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [12]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [13]:
# write your numpy code here
def unknown_signature(arr):
    mask = (arr % 2 == 0) & ((arr % 3 == 0) | (arr > 10))
    modified_arr = ((arr ^ 7) + 2)[mask]
    return modified_arr

my_array = np.array([6, 9, 12, 14, 17, 20])
unknown_signature(my_array)


array([ 3, 13, 11, 21], dtype=int32)